// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRJBSpWi43Qgl2atCsfXyxFobfEfte2I',
    appId: '1:54887374121:web:d42818c7ffe288b9ca6b38',
    messagingSenderId: '54887374121',
    projectId: 'qr-studio-app-495d5',
    authDomain: 'qr-studio-app-495d5.firebaseapp.com',
    storageBucket: 'qr-studio-app-495d5.firebasestorage.app',
    measurementId: 'G-XE6TRB0G4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0FSdm0PtFW0PQo1gtBVsx1fUeKuRKs-c',
    appId: '1:54887374121:android:b72b488d2fc2a334ca6b38',
    messagingSenderId: '54887374121',
    projectId: 'qr-studio-app-495d5',
    storageBucket: 'qr-studio-app-495d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3q2RlrRl-17ZNeFbFEd4M_3McWSKt_H8',
    appId: '1:54887374121:ios:35932911cc593684ca6b38',
    messagingSenderId: '54887374121',
    projectId: 'qr-studio-app-495d5',
    storageBucket: 'qr-studio-app-495d5.firebasestorage.app',
    iosBundleId: 'com.example.qrStudioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3q2RlrRl-17ZNeFbFEd4M_3McWSKt_H8',
    appId: '1:54887374121:ios:35932911cc593684ca6b38',
    messagingSenderId: '54887374121',
    projectId: 'qr-studio-app-495d5',
    storageBucket: 'qr-studio-app-495d5.firebasestorage.app',
    iosBundleId: 'com.example.qrStudioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRJBSpWi43Qgl2atCsfXyxFobfEfte2I',
    appId: '1:54887374121:web:7439193630e0eaf7ca6b38',
    messagingSenderId: '54887374121',
    projectId: 'qr-studio-app-495d5',
    authDomain: 'qr-studio-app-495d5.firebaseapp.com',
    storageBucket: 'qr-studio-app-495d5.firebasestorage.app',
    measurementId: 'G-CB4TZQ8LW9',
  );
}
